# This is an array of all those folders that contain video data for signs. Change it once more data is added with its own sign meaning in alphabetical order.
signs_lib = {
    'a': 'a',
    'abols': 'ābols',
    'ah': 'ā', 
    'b': 'b', 
    'c': 'c', 
    'ch': 'č', 
    'd': 'd', 
    'e': 'e', 
    'eh': 'ē', 
    'f': 'f', 
    'g': 'g',
    'garso': 'garšo', 
    'gh': 'ģ', 
    'h': 'h', 
    'i': 'i', 
    'ih': 'ī', 
    'j': 'j', 
    'k': 'k', 
    'kh': 'ķ', 
    'l': 'l',
    'labdien': 'labdien', 
    'lh': 'ļ', 
    'm': 'm',
    'macities': 'mācīties',
    'man': 'man', 
    'n': 'n', 
    'nh': 'ņ', 
    'o': 'o', 
    'p': 'p',
    'paldies': 'paldies',
    'patikt': 'patikt',
    'r': 'r', 
    's': 's', 
    'sauc': 'sauc',
    'sh': 'š', 
    't': 't', 
    'u': 'u', 
    'uh': 'ū',
    'un': 'un',
    'uz_redzesanos': 'uz redzēšanos', 
    'v': 'v', 
    'z': 'z', 
    'zh': 'ž',
    '_': '_'
}